site_name: Programmering 1

copyright: © 2025 Emil Frisk


# ---THEME---
theme:
  name: material
  language: sv

  # Features
  features:
    - navigation.top
    - navigation.footer
    # - header.autohide
    # - search.suggest
    - search.highlight

  # Ikoner
  icon:
    logo: material/console
    # favicon: måste va en bild som ligger i docs i projektet tror jag
    menu: material/console
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  # Färger
  # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue grey, black, white
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode


# ---EXTRA CSS---
extra_css:
  - stylesheets/extra.css
  - stylesheets/print.css

  
# ---NAVIGATION---
nav:                          
  - Hem: index.md
  - 1. Grundläggande:                   # Kan delas in i grupper med indentering
      - Datorer & programmering: content/modul-1/datorer-och-programmering.md
      - Variabler: content/modul-1/variabler.md
      - Datatyper: content/modul-1/datatyper.md
      - Operatorer: content/modul-1/operatorer.md
      - Typkonvertering: content/modul-1/typkonvertering.md
      - Slumptal: content/modul-1/slump.md
      - Begrepp: content/modul-1/_begrepp01.md
      - Övningsuppgifter: content/modul-1/_uppg01.md
      - Lösningsförslag: content/modul-1/_lösn01.md

  - 2. Villkor och logik:
      - Villkorssatser: content/modul-2/villkorssatser.md
      - If-sats: content/modul-2/villkor-if.md
      - Switch: content/modul-2/villkor-switch.md
      - Felhantering: content/modul-2/felhantering.md
      - ReadKey: content/modul-2/readkey.md
      - Villkorsoperatorn: content/modul-2/villkorsoperatorn.md
      - Begrepp: content/modul-2/_begrepp02.md
      - Uppgifter: content/modul-2/_uppg02.md
      - Lösningar: content/modul-2/_lösn02.md

  - 3. Upprepning och data:
      - Repetitionssatser: content/modul-3/repetitionssatser.md
      - Strängarhantering och formatering: content/modul-3/strängar-format.md
      - Filhantering: content/modul-3/filhantering.md
      - Algoritmer, pseudokod & aktivitetsdiagram: content/modul-3/alg-pseudo-aktdiag.md
      - Begrepp: content/modul-3/_begrepp03.md
      - Uppgifter: content/modul-3/_uppg03.md
      - Lösningar: content/modul-3/_lösn03.md

  - 4. Metoder och arrayer:
      - Metoder: content/modul-4/metoder.md
      - Arrayer: content/modul-4/arrayer.md
      - Begrepp: content/modul-4/_begrepp04.md
      - Uppgifter: content/modul-4/_uppg04.md
      - Lösningar: content/modul-4/_lösn04.md

  - 5. Listor och dictionaries:
      - Listor: content/modul-5/listor.md
      - Dictionaries: content/modul-5/dictionaries.md
      - Referenstyp och värdetyp: content/modul-5/ref-värdetyp.md
      - Begrepp: content/modul-5/_begrepp05.md
      - Uppgifter: content/modul-5/_uppg05.md
      - Lösningar: content/modul-5/_lösn05.md

  - 6. Klasser och objekt:
      - Introduktion: content/modul-6/klasser-objekt-intro.md
      - Konstruktorer: content/modul-6/konstruktorer.md
      - Properties i C#: content/modul-6/properties.md
      - Begrepp: content/modul-6/_begrepp06.md
      - Uppgifter: content/modul-6/_uppg06.md
      - Lösningar: content/modul-6/_lösn06.md

  - 7. MonoGame: content/modul-7/monoguide-old.md




# ---MARKDOWN---
# Rekommenderade setupen från mkdocs-material dokumentationen
# Emojigrejerna är felaktigt lintade i yaml i vscode, inget eg. problem
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# ---ÖVRIGT---
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:emil.frisk@ulricehamn.se